import Head from "next/head";

import UsersList from "../componets/complex/user-list";
import { Layout } from "../componets/containers/layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../assets/images/logo-favicon.png" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Layout>
        <UsersList />
      </Layout>
    </>
  );
}
