import Head from 'next/head';

import Auth from './auth';

const Home = () => {
  return (
    <>
      <Head>
        <title>Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../assets/images/logo-favicon.png" />
        {/*<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap" rel="stylesheet" />*/}
      </Head>

      <Auth />
    </>
  );
};

export default Home;
